{
  "info": {
    "title": "AI智能助手",
    "description": "",
    "version": "1.0.0",
    "x-project-id": "5114af8cdc71000",
    "x-marks": [
      {
        "mark_id": "1",
        "project_id": "0",
        "name": "开发中",
        "color": "#2857FF",
        "is_sys_default": 1,
        "is_default_mark": 1
      },
      {
        "mark_id": "2",
        "project_id": "0",
        "name": "已完成",
        "color": "#26CEA4",
        "is_sys_default": 1,
        "is_default_mark": -1
      },
      {
        "mark_id": "3",
        "project_id": "0",
        "name": "需修改",
        "color": "#FFC01E",
        "is_sys_default": 1,
        "is_default_mark": -1
      },
      {
        "mark_id": "4",
        "project_id": "0",
        "name": "已废弃",
        "color": "#FF2200",
        "is_sys_default": 1,
        "is_default_mark": -1
      }
    ]
  },
  "openapi": "3.0.0",
  "components": {
    "schemas": {
      "公告详细信息": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "标题，纯文本",
            "x-schema-mock": "标题"
          },
          "pinSort": {
            "type": [
              "integer",
              "null"
            ],
            "description": "置顶排序，默认为空，有数字时从大到小排在最前，后续按规则排序",
            "x-schema-mock": "1"
          },
          "content": {
            "type": "string",
            "description": "公告内容，HTML 格式",
            "x-schema-mock": "<h1>你好</h1>"
          },
          "status": {
            "type": "boolean",
            "description": "状态，已启用，未启用",
            "x-schema-mock": "true"
          },
          "createTime": {
            "type": "string",
            "description": "创建时间",
            "x-schema-mock": "2026-05-18 14:30:00"
          },
          "availableTime": {
            "type": "string",
            "description": "发布时间",
            "x-schema-mock": "2026-05-18 14:30:00"
          },
          "id": {
            "type": "integer",
            "description": "公告 ID",
            "x-schema-mock": "1"
          }
        }
      },
      "公告列表项": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "标题，纯文本",
            "x-schema-mock": "标题"
          },
          "pinSort": {
            "type": [
              "integer",
              "null"
            ],
            "description": "置顶排序，默认为空，有数字时从大到小排在最前，后续的规则按规则排序",
            "x-schema-mock": "1"
          },
          "status": {
            "type": "boolean",
            "description": "状态，已启用，未启用",
            "x-schema-mock": "true"
          },
          "availableTime": {
            "type": "string",
            "description": "发布时间",
            "x-schema-mock": "2026-05-18 14:30:00"
          },
          "id": {
            "type": "string",
            "default": "1",
            "description": "公告 ID",
            "x-schema-mock": "1"
          }
        }
      },
      "响应框架": {
        "type": "object",
        "required": [
          "status",
          "message",
          "data"
        ],
        "properties": {
          "status": {
            "type": "integer",
            "description": "状态码",
            "x-schema-mock": "100"
          },
          "message": {
            "type": "string",
            "description": "提示",
            "x-schema-mock": "操作成功"
          },
          "data": {
            "type": "object",
            "required": [],
            "properties": {},
            "description": "数据体"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "开放端",
      "description": "",
      "x-type": "folder",
      "x-url": "",
      "x-target-id": "13c15f40f84183"
    },
    {
      "name": "01、统一控制",
      "description": "",
      "x-type": "folder",
      "x-url": "",
      "x-target-id": "2a79cc68704c08"
    },
    {
      "name": "02、功能模块",
      "description": "",
      "x-type": "folder",
      "x-url": "",
      "x-target-id": "2cb9cb01b040d2"
    },
    {
      "name": "视频生成",
      "description": "",
      "x-type": "folder",
      "x-url": "",
      "x-target-id": "2cb9cb01b040e6"
    },
    {
      "name": "素材管理",
      "description": "",
      "x-type": "folder",
      "x-url": "",
      "x-target-id": "39ce5bb9f041a3"
    },
    {
      "name": "官方版",
      "description": "",
      "x-type": "folder",
      "x-url": "",
      "x-target-id": "3c9c3e7df764e3"
    },
    {
      "name": "渠道-素材模块-暂未开放",
      "description": "",
      "x-type": "folder",
      "x-url": "",
      "x-target-id": "3cb35accb7659e"
    }
  ],
  "paths": {
    "/auth/getToken": {
      "post": {
        "x-target-id": "2a7a17acb04c62",
        "x-protocol": "http",
        "summary": "01、获取token",
        "description": "",
        "tags": [
          "账户信息"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-06-25T16:31:36+08:00",
        "x-updated-user-name": "路过一小只",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "account": {
                    "type": "string",
                    "description": "",
                    "example": "jkp0001"
                  },
                  "password": {
                    "type": "string",
                    "description": "",
                    "example": "abc123456"
                  }
                },
                "required": [
                  "account",
                  "password"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 100,
                  "message": "操作成功",
                  "data": "3ebb95074ad7e4fccd2791e908614efb",
                  "sign": "D3VkL2/STIhcEdWF3QV+a8CWzU48jOX9tn2KyR7pn8/izP4d9lsU8951DBMUXWoHvp2ZTd/wqU8qhN84IfxQYrUkp4WObVO9cBXLbuzHQuaqrGlNHCE99z8IOhUc4Cv3BzIC2p32nuhRchgl2M0tbcnbqIIWyRevRGTdBItUr95/Suk0rdGa64b+oqf/q6Cz0Gpu7fjg08Lwl3apboNYcWhLTI19mmDSAn1H6kuYCOQKuruoWCVh+IuKYfuX4neGpis8wDyGXbsYYKE5N/v2DmC8xiILUGCTaHoYlbqsgtShUTv1YtveRY/3CsVQxwyJd0sdCH9T+qKMir4w17dSbw=="
                }
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/workflow/seedanceDiscountChannel1": {
      "post": {
        "x-target-id": "419cad4b7663d",
        "x-protocol": "http",
        "summary": "Seedance2.0体验版",
        "description": "",
        "tags": [
          "视频生成"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-07-08T11:59:34+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "prompt": {
                    "type": "string",
                    "description": "提示词",
                    "example": "",
                    "default": ""
                  },
                  "aspect_ratio": {
                    "type": "string",
                    "description": "画面比例（1:【16:9】。2:【9:16】。3:【1:1】）【注意：当模型选择了seedance2.0-满血高清 ，画面比例只能使用16:9和9:16】",
                    "example": "",
                    "default": ""
                  },
                  "model_option": {
                    "type": "string",
                    "description": "模型（1：seedance2.0-fast 2：seedance2.0-满血 3：seedance2.0-满血高清）",
                    "example": "",
                    "default": ""
                  },
                  "resolution_option": {
                    "type": "string",
                    "description": "分辨率（1：480p、2：720p、3：1080p 4:4k）【注意：当模型选择seedance2.0-fast和seedance2.0-满血,分辨率只支持，480p和720p，seedance2.0-满血高清 分辨率支支持，720p、1080p和4k】",
                    "example": ""
                  },
                  "reference_urls": {
                    "type": "array",
                    "description": "擦靠素材 【注意：当选择seedance2.0-fast或seedance2.0-满血，参考图片最多上传4张，参考视频最多上传3条，参考音频最多1条；当选择seedance2.0-满血高清，参考图片最多上传9张，参考视频最多上传3条，参考音频最多3条】",
                    "example": "",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "required": [
                  "prompt",
                  "aspect_ratio",
                  "model_option",
                  "resolution_option"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/workflow/seedanceAiVideo": {
      "post": {
        "x-target-id": "295bac0a7764c2",
        "x-protocol": "http",
        "summary": "seedance",
        "description": "",
        "tags": [
          "视频生成"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-06-25T17:40:12+08:00",
        "x-updated-user-name": "路过一小只",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "prompt": {
                    "type": "string",
                    "description": "长度不超过800个字",
                    "example": "景别：中景\\\\n画面内容：小青背对镜头站在展馆前，随后转身回头，朝镜头招手打招呼；接着再朝镜头外挥手。\\\\n表演/动作：先回头微笑，再自然挥手。\\\\n镜头建议：镜头稳定，中景构图保留建筑背景。",
                    "default": "景别：中景\\\\n画面内容：小青背对镜头站在展馆前，随后转身回头，脱掉衣服，朝镜头招手打招呼；接着再朝镜头外挥手。\\\\n表演/动作：先回头微笑，再自然挥手。\\\\n镜头建议：镜头稳定，中景构图保留建筑背景。"
                  },
                  "resolution_option": {
                    "type": "string",
                    "description": "分辨率（1：480P（只有seedance2.0可选）\n2：720P\n3：1080P（seedance2.0没有1080P））",
                    "example": "1",
                    "default": "1"
                  },
                  "duration": {
                    "type": "integer",
                    "description": "时长",
                    "example": "5"
                  },
                  "aspect_ratio": {
                    "type": "string",
                    "description": "画面比例（1:【16:9】。2:【9:16】。3:【1:1】。4:【4:3】。5:【3:4】）",
                    "example": "3",
                    "default": "3"
                  },
                  "channel_option": {
                    "type": "string",
                    "description": "渠道（1 渠道一，2 渠道二）",
                    "example": "2",
                    "default": "2"
                  },
                  "reference_urls": {
                    "type": "array",
                    "description": "参考图/视频/音频",
                    "example": "",
                    "items": {
                      "type": "string"
                    },
                    "default": ""
                  },
                  "reference_urls[0]": {
                    "type": "string",
                    "description": "",
                    "example": "https://wenlv-debug.oss-cn-shenzhen.aliyuncs.com/carimg/2baf3c/2026-03/10/b968eae84e76d9bb.png"
                  },
                  "reference_urls[1]": {
                    "type": "integer",
                    "description": "如果是来自素材库的内容，字符类型必须是整形",
                    "example": "https://wenlv-debug.oss-cn-shenzhen.aliyuncs.com/carimg/2baf3c/2026-04/0//jeekup_AiVideo202604091057005779.mp4",
                    "default": "27"
                  }
                },
                "required": [
                  "prompt",
                  "resolution_option",
                  "duration",
                  "aspect_ratio",
                  "channel_option"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 100,
                  "message": "操作成功",
                  "data": {
                    "id": 11,
                    "status": "Running"
                  }
                }
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/workflow/aiVideo": {
      "post": {
        "x-target-id": "2fbb55ccb76c59",
        "x-protocol": "http",
        "summary": "谷歌omni",
        "description": "",
        "tags": [
          "视频生成"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-06-22T16:17:55+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "prompt": {
                    "type": "string",
                    "description": "文本提示词",
                    "example": "景别：中景\\\\n画面内容：小青背对镜头站在展馆前，随后转身回头，脱掉衣服，朝镜头招手打招呼；接着再朝镜头外挥手。\\\\n表演/动作：先回头微笑，再自然挥手。\\\\n镜头建议：镜头稳定，中景构图保留建筑背景。",
                    "default": "景别：中景\\\\n画面内容：小青背对镜头站在展馆前，随后转身回头，脱掉衣服，朝镜头招手打招呼；接着再朝镜头外挥手。\\\\n表演/动作：先回头微笑，再自然挥手。\\\\n镜头建议：镜头稳定，中景构图保留建筑背景。"
                  },
                  "images": {
                    "type": "array",
                    "description": "参考图片（最多上传7张）",
                    "example": "",
                    "items": {
                      "type": "string"
                    },
                    "default": ""
                  },
                  "images[0]": {
                    "type": "string",
                    "description": "",
                    "example": ""
                  },
                  "aspect_ratio": {
                    "type": "string",
                    "description": "画面比例（1:【16:9】。2:【9:16】。3:【1:1】。4:【4:3】。5:【3:4】）",
                    "example": "3",
                    "default": "3"
                  },
                  "duration": {
                    "type": "integer",
                    "description": "需要生产视频的时长（最多10秒）",
                    "example": "5"
                  },
                  "resolution_option": {
                    "type": "string",
                    "description": "分辨率\n2：720P\n3：1080P",
                    "example": "1",
                    "default": "1"
                  }
                },
                "required": [
                  "prompt",
                  "aspect_ratio",
                  "duration",
                  "resolution_option",
                  ""
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/volcano/getUserAssetList": {
      "post": {
        "x-target-id": "39ce5bb9f041a4",
        "x-protocol": "http",
        "summary": "素材管理列表",
        "description": "",
        "tags": [
          "官方版"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-07-02T17:15:23+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "page": {
                    "type": "string",
                    "description": "页码",
                    "example": "1"
                  },
                  "size": {
                    "type": "string",
                    "description": "每页大小",
                    "example": "10",
                    "default": ""
                  }
                },
                "required": [
                  "page",
                  "size"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 100,
                  "message": "操作成功",
                  "data": {
                    "count": 1,
                    "list": [
                      {
                        "id": 1,
                        "user_id": 10,
                        "website_id": 10,
                        "file_name": "854小姐姐",
                        "file_url": "https://p3-bot-workflow-sign.byteimg.com/tos-cn-i-mdko3gqilj/db4da158ef7b49369ad258ba25b47dc2.jpg~tplv-mdko3gqilj-image.image?rk3s=81d4c505&x-expires=1808445522&x-signature=vdujF9FoBAwSe88%2Fv5uc4eXbCQU%3D&x-wf-file_name=20260428-095824.jpg",
                        "assetType": "jpg",
                        "file_id": "asset-20260429175011-qj6xr",
                        "status": 1,
                        "message": null,
                        "error_code": null,
                        "is_delete": 0,
                        "create_time": "2026-04-29 17:50:11",
                        "update_time": "2026-04-29 17:50:11"
                      }
                    ]
                  }
                }
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/volcano/uploadAsset": {
      "post": {
        "x-target-id": "39ce5bb9f041a5",
        "x-protocol": "http",
        "summary": "上传素材",
        "description": "",
        "tags": [
          "官方版"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-07-02T17:15:29+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file_name": {
                    "type": "string",
                    "description": "文件名",
                    "example": "854小姐姐"
                  },
                  "file_url": {
                    "type": "string",
                    "description": "文件链接",
                    "example": "https://p3-bot-workflow-sign.byteimg.com/tos-cn-i-mdko3gqilj/db4da158ef7b49369ad258ba25b47dc2.jpg~tplv-mdko3gqilj-image.image?rk3s=81d4c505&x-expires=1808445522&x-signature=vdujF9FoBAwSe88%2Fv5uc4eXbCQU%3D&x-wf-file_name=20260428-095824.jpg"
                  }
                },
                "required": [
                  "file_name",
                  "file_url"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/volcano/delAsset": {
      "post": {
        "x-target-id": "39ce5bb9f041a6",
        "x-protocol": "http",
        "summary": "删除素材",
        "description": "",
        "tags": [
          "官方版"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-07-02T17:15:35+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "description": "ID",
                    "example": "1",
                    "default": "1"
                  }
                },
                "required": [
                  "id"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/volcano/editAsset": {
      "post": {
        "x-target-id": "39ce5bb9f041a7",
        "x-protocol": "http",
        "summary": "更新素材名",
        "description": "",
        "tags": [
          "官方版"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-07-02T17:15:32+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "description": "ID",
                    "example": "1",
                    "default": "1"
                  },
                  "file_name": {
                    "type": "string",
                    "description": "文件名",
                    "example": "aaaaaa",
                    "default": ""
                  }
                },
                "required": [
                  "id",
                  "file_name"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/volcano/getAssetStatus": {
      "post": {
        "x-target-id": "39ce6f383041a8",
        "x-protocol": "http",
        "summary": "获取素材审核结果",
        "description": "",
        "tags": [
          "官方版"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-07-02T17:15:38+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "description": "ID",
                    "example": "1",
                    "default": "1"
                  }
                },
                "required": [
                  "id"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 100,
                  "message": "操作成功",
                  "data": {
                    "id": 1,
                    "status": 1,
                    "file_name": "854小姐姐",
                    "message": null
                  }
                }
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/workflow/liveAiVideo": {
      "post": {
        "x-target-id": "3af90191f04561",
        "x-protocol": "http",
        "summary": "seedance（支持人脸）",
        "description": "",
        "tags": [
          "视频生成"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-06-22T13:58:08+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "prompt": {
                    "type": "string",
                    "description": "文本提示词",
                    "example": "景别：中景\\\\n画面内容：小青背对镜头站在展馆前，随后转身回头，脱掉衣服，朝镜头招手打招呼；接着再朝镜头外挥手。\\\\n表演/动作：先回头微笑，再自然挥手。\\\\n镜头建议：镜头稳定，中景构图保留建筑背景。",
                    "default": "景别：中景\\\\n画面内容：小青背对镜头站在展馆前，随后转身回头，脱掉衣服，朝镜头招手打招呼；接着再朝镜头外挥手。\\\\n表演/动作：先回头微笑，再自然挥手。\\\\n镜头建议：镜头稳定，中景构图保留建筑背景。"
                  },
                  "resolution_option": {
                    "type": "string",
                    "description": "分辨率（1：480P（只有seedance2.0可选）\n2：720P\n3：1080P（seedance2.0没有1080P））",
                    "example": "1",
                    "default": "1"
                  },
                  "duration": {
                    "type": "string",
                    "description": "时长",
                    "example": "5",
                    "default": "5"
                  },
                  "aspect_ratio": {
                    "type": "string",
                    "description": "画面比例（1:【16:9】。2:【9:16】。3:【1:1】。4:【4:3】。5:【3:4】）",
                    "example": "3",
                    "default": "3"
                  },
                  "channel_option": {
                    "type": "string",
                    "description": "渠道（1 渠道一）",
                    "example": "1",
                    "default": "2"
                  },
                  "reference_urls": {
                    "type": "array",
                    "description": "参考图/视频/音频视频:（仅支持mp4、mov格式，分辨率480P、、720P，时长2~15s(总时长不超过15s)，单视频不超过50MB;\n图片:单图小于30MB(总大小不超过64MB)\n音频:仅支持wav、mp3格式，时长2~15s，单个音频不超过15MB;）\n",
                    "example": "",
                    "items": {
                      "type": "string"
                    },
                    "default": ""
                  },
                  "reference_urls[0]": {
                    "type": "string",
                    "description": "",
                    "example": "https://wenlv-debug.oss-cn-shenzhen.aliyuncs.com/carimg/2baf3c/2026-03/10/b968eae84e76d9bb.png"
                  },
                  "reference_urls[1]": {
                    "type": "integer",
                    "description": "如果是来自素材库的内容，字符类型必须是整形",
                    "example": "27",
                    "default": "27"
                  }
                },
                "required": [
                  "prompt",
                  "resolution_option",
                  "duration",
                  "aspect_ratio",
                  "channel_option"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 100,
                  "message": "操作成功",
                  "data": {
                    "id": 11,
                    "status": "Running"
                  }
                }
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/workflow/seedanceDiscount": {
      "post": {
        "x-target-id": "3c9dc00db7653e",
        "x-protocol": "http",
        "summary": "渠道1-seedance（支持人脸）-暂未开放",
        "description": "",
        "tags": [
          "视频生成"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-07-07T18:38:17+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "prompt": {
                    "type": "string",
                    "description": "文本提示词",
                    "example": "景别：中景\\\\n画面内容：小青背对镜头站在展馆前，随后转身回头，脱掉衣服，朝镜头招手打招呼；接着再朝镜头外挥手。\\\\n表演/动作：先回头微笑，再自然挥手。\\\\n镜头建议：镜头稳定，中景构图保留建筑背景。",
                    "default": "景别：中景\\\\n画面内容：小青背对镜头站在展馆前，随后转身回头，脱掉衣服，朝镜头招手打招呼；接着再朝镜头外挥手。\\\\n表演/动作：先回头微笑，再自然挥手。\\\\n镜头建议：镜头稳定，中景构图保留建筑背景。"
                  },
                  "resolution_option": {
                    "type": "string",
                    "description": "分辨率（1：480P（只有seedance2.0可选）\n2：720P\n3：1080P（seedance2.0没有1080P））",
                    "example": "1",
                    "default": "1"
                  },
                  "duration": {
                    "type": "string",
                    "description": "时长",
                    "example": "5",
                    "default": "5"
                  },
                  "aspect_ratio": {
                    "type": "string",
                    "description": "画面比例（1:【16:9】。2:【9:16】。3:【1:1】。4:【4:3】。5:【3:4】）",
                    "example": "3",
                    "default": "3"
                  },
                  "reference_urls": {
                    "type": "array",
                    "description": "参考图/视频/音频视频:（仅支持mp4、mov格式，分辨率480P、、720P，时长2~15s(总时长不超过15s)，单视频不超过50MB;\n图片:单图小于30MB(总大小不超过64MB)\n音频:仅支持wav、mp3格式，时长2~15s，单个音频不超过15MB;）\n",
                    "example": "",
                    "items": {
                      "type": "string"
                    },
                    "default": ""
                  },
                  "reference_urls[0]": {
                    "type": "string",
                    "description": "",
                    "example": "https://wenlv-debug.oss-cn-shenzhen.aliyuncs.com/carimg/2baf3c/2026-03/10/b968eae84e76d9bb.png"
                  },
                  "reference_urls[1]": {
                    "type": "integer",
                    "description": "如果是来自素材库的内容，字符类型必须是整形",
                    "example": "27",
                    "default": "27"
                  }
                },
                "required": [
                  "prompt",
                  "resolution_option",
                  "duration",
                  "aspect_ratio"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 100,
                  "message": "操作成功",
                  "data": {
                    "id": 11,
                    "status": "Running"
                  }
                }
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/material/getUserAssetList": {
      "post": {
        "x-target-id": "3cb35accb7659f",
        "x-protocol": "http",
        "summary": "素材库列表",
        "description": "",
        "tags": [
          "渠道-素材模块-暂未开放"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-07-02T17:35:19+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {}
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/material/uploadAsset": {
      "post": {
        "x-target-id": "3cb35accb765a0",
        "x-protocol": "http",
        "summary": "上传素材",
        "description": "",
        "tags": [
          "渠道-素材模块-暂未开放"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-07-02T17:54:09+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file_name": {
                    "type": "string",
                    "description": "文件名",
                    "example": "854小姐姐"
                  },
                  "file_url": {
                    "type": "string",
                    "description": "文件链接",
                    "example": "https://p3-bot-workflow-sign.byteimg.com/tos-cn-i-mdko3gqilj/db4da158ef7b49369ad258ba25b47dc2.jpg~tplv-mdko3gqilj-image.image?rk3s=81d4c505&x-expires=1808445522&x-signature=vdujF9FoBAwSe88%2Fv5uc4eXbCQU%3D&x-wf-file_name=20260428-095824.jpg"
                  }
                },
                "required": [
                  "file_name",
                  "file_url"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/material/delAsset": {
      "post": {
        "x-target-id": "3cb35accb765a1",
        "x-protocol": "http",
        "summary": "删除素材",
        "description": "",
        "tags": [
          "渠道-素材模块-暂未开放"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-07-02T17:35:19+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "description": "ID",
                    "example": "54",
                    "default": "1"
                  }
                },
                "required": [
                  "id"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/material/editAsset": {
      "post": {
        "x-target-id": "3cb35accf765a2",
        "x-protocol": "http",
        "summary": "更新素材名",
        "description": "",
        "tags": [
          "渠道-素材模块-暂未开放"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-07-02T17:35:19+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "description": "ID",
                    "example": "1",
                    "default": "1"
                  },
                  "file_name": {
                    "type": "string",
                    "description": "文件名",
                    "example": "aaaaaa",
                    "default": ""
                  }
                },
                "required": [
                  "id",
                  "file_name"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/material/delAssets": {
      "post": {
        "x-target-id": "3cb35accf765a3",
        "x-protocol": "http",
        "summary": "批量删除素材",
        "description": "",
        "tags": [
          "渠道-素材模块-暂未开放"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-07-02T17:35:19+08:00",
        "x-updated-user-name": "zhenfeng",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "ids": {
                    "type": "array",
                    "description": "ID",
                    "example": "",
                    "items": {
                      "type": "string"
                    },
                    "default": ""
                  },
                  "ids[0]": {
                    "type": "string",
                    "description": "",
                    "example": "1"
                  },
                  "ids[1]": {
                    "type": "string",
                    "description": "",
                    "example": "2"
                  }
                },
                "required": [
                  "ids",
                  "ids[0]",
                  "ids[1]"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/auth/getMyPower": {
      "post": {
        "x-target-id": "3edabf95f0425f",
        "x-protocol": "http",
        "summary": "02、获取算力",
        "description": "",
        "tags": [
          "账户信息"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-05-15T16:45:04+08:00",
        "x-updated-user-name": "zhenfeng",
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 100,
                  "message": "操作成功",
                  "data": 1008583
                }
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    },
    "/workflow/getResult": {
      "post": {
        "x-target-id": "3ee4509f7042ec",
        "x-protocol": "http",
        "summary": "获取生成结果",
        "description": "",
        "tags": [
          "视频生成"
        ],
        "x-mock-server-enable": 1,
        "x-mark-id": "2",
        "x-updated-at": "2026-06-20T21:36:41+08:00",
        "x-updated-user-name": "路过一小只",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "number",
                    "description": "会话ID",
                    "example": "1"
                  }
                },
                "required": [
                  "id"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": {
                  "status": 100,
                  "message": "操作成功",
                  "data": {
                    "id": 20,
                    "status": "Success",
                    "response_json": "Example content."
                  }
                }
              }
            }
          },
          "404": {
            "description": "失败",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                },
                "example": ""
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "",
      "description": "uat环境",
      "x-env-id": "",
      "variables": {
        "codekey": {
          "default": "",
          "description": ""
        },
        "enterpriseToken": {
          "default": "xxxx",
          "description": ""
        },
        "toadminurl": {
          "default": "http://admin.aiassistant.uat.jeekup.top",
          "description": ""
        },
        "ContentType": {
          "default": "application/json",
          "description": ""
        },
        "mur": {
          "default": "xxxxx",
          "description": ""
        },
        "toenterprise": {
          "default": "localhost:9506",
          "description": ""
        },
        "Originadmin": {
          "default": "localhost:9506",
          "description": ""
        },
        "Originenterprise": {
          "default": "localhost:9506",
          "description": ""
        },
        "Time": {
          "default": "122",
          "description": ""
        },
        "adminToken": {
          "default": "xxxx",
          "description": ""
        },
        "code": {
          "default": "",
          "description": ""
        }
      }
    }
  ]
}
